### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by teinett**
Added installation of package unist-builder. 
The example in readme.md file doesn't work without it.

### CODE REVIEW

**Review by ChristianMurphy — CHANGES_REQUESTED** [review]
`unist-builder` is not required to use the module.
It is shown in the example, but `unist-util-visit` works fine independently.

A potential ideas to help clarify this:
* add a "`unist-builder` is used here" type note to the `use` section
* or update the example to use plain JSON, rather than a builder
* or something else

Thoughts? :thought_balloon:

**Comment by teinett** [comment]
I tried to use the code of example without "npm install unist-builder". The example gives the error:

ast

**Comment by wooorm** [comment]
Could you answer @ChristianMurphy’s comment?

**Comment by ChristianMurphy** [comment]
> I tried to use the code of example without `npm install unist-builder`. The example gives the error ...

Right, "install" shows how to install _this_ module, "use" provides an example of _this_ module used along side _another_ module.

For example, consider if the example was replaced with

```ts
import {visit} from 'unist-util-visit'
import remark from 'remark'

const tree = remark().parse('Some _emphasis_, **importance**, and `code`.')

visit(tree, (node) => console.log(node))
```

this shows usage with `remark`, wiwithout `unist-builder`.
`unist-util-visit` is the key part here, not `remark` or `unist-builder`, encouraging installing a dependency which is not needed could cause confusion and/or add an unnecessary dependency.

**Comment by teinett** [comment]
**For beginners**, it would be helpful to have a readme part "Don't forget" with text, how to use the example from zero

```
Don't forget to install all dependencies for this example: `npm install unist-builder unist-util-visit`
```

**Comment by ChristianMurphy** [comment]
> For beginners, it would be helpful to have a readme part "Don't forget" with text, how to use the example from zero

I agree, that's one of the suggestions from https://github.com/syntax-tree/unist-util-visit/pull/26#pullrequestreview-698271392
Would you be interested in updating the readme to include that, or one of the other suggestions?

**Comment by teinett** [comment]
> Would you be interested in updating the readme to include that, or one of the other suggestions?
I didn't know how to change this pull request, so I created the new one: https://github.com/syntax-tree/unist-util-visit/pull/27.

If it's OK for you, I can update other readme files with the same pattern.

**Comment by teinett** [comment]
Changed in https://github.com/syntax-tree/unist-util-visit/pull/27

**Pull request closed without merging**
